#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Plugins.Extensions.OpenWebif.local import tstrings

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1406885499.292713
__CHEETAH_genTimestamp__ = 'Fri Aug  1 18:31:39 2014'
__CHEETAH_src__ = '/home/wslee2/models/5-wo/force1plus/openpli3.0/build-force1plus/tmp/work/mips32el-oe-linux/enigma2-plugin-extensions-openwebif-1+git5+3c0c4fbdb28d7153bf2140459b553b3d5cdd4149-r0/git/plugin/controllers/views/ajax/at.tmpl'
__CHEETAH_srcLastModified__ = 'Fri Aug  1 18:30:05 2014'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class at(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(at, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        _orig_filter_29289843 = _filter
        filterName = u'WebSafe'
        if self._CHEETAH__filters.has_key("WebSafe"):
            _filter = self._CHEETAH__currentFilter = self._CHEETAH__filters[filterName]
        else:
            _filter = self._CHEETAH__currentFilter = \
			self._CHEETAH__filters[filterName] = getattr(self._CHEETAH__filtersLib, filterName)(self).filter
        write(u'''<style>
  #atlist .ui-selecting { background: #FECA40; }
  #atlist .ui-selected { background: #F39814; color: white; }
  #atlist { list-style-type: none; margin: 0; padding: 0; }
  #atlist li { margin: 3px; padding: 0.4em; font-size: 1.4em; height: 18px; }
  optgroup {font-weight: bolder;}
fieldset > label
{
\t-webkit-margin-top-collapse: separate;
\tmargin-top: 1.5em;
\tdisplay: inline-block;
}
</style>

<div id="content_main" style="min-height: 500px;">
\t<div id="info">
\t\t<h3>AutoTimer</h3>

\t\t<div style="background-color: #00000">
\t\t
\t\t<div style="display: inline-block; width: 100%; zoom: 1;">
\t\t\t<div style="float:left;width:200px;">
\t\t\t\t<h3>AutoTimer List</h3>
\t\t\t\t<ol id="atlist">
\t\t\t\t</ol>
\t\t\t\t
\t\t\t</div>
\t\t\t<div style="margin-left:200px;">
\t\t\t\t<div style="display: inline-block; width: 100%; zoom: 1;">
\t\t\t\t\t<h3>AutoTimer Edit <span id=\'at_name\'></span></h3>
\t\t\t\t\t<div id="ateditcontent">
\t\t\t\t\t\t<form>
\t\t\t\t\t\t\t<fieldset>
\t\t\t\t\t\t\t\t<br><label for="enabled">Enabled:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="enabled" id="enabled" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t<label for="name">''')
        _v = VFFSL(SL,"tstrings",True)['name'] # u"$tstrings['name']" on line 38, col 27
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['name']")) # from line 38, col 27.
        write(u''':</label>
\t\t\t\t\t\t\t\t<input type="text" name="name" id="name" class="text ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t<label for="match">Match:</label>
\t\t\t\t\t\t\t\t<input type="text" name="match" id="match" class="text ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t<br><label for="encoding">Encoding:</label>
\t\t\t\t\t\t\t\t<select name="encoding" id="encoding">
\t\t\t\t\t\t\t\t<option value="ISO8859-15" selected="selected">ISO8859-15</option>
\t\t\t\t\t\t\t\t<option value="UTF-8">UTF-8</option>
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t<label for="searchType">Search type:</label>
\t\t\t\t\t\t\t\t<select name="searchType" id="searchType">
\t\t\t\t\t\t\t\t<option value="partical" selected="selected">partical match</option>
\t\t\t\t\t\t\t\t<option value="exact">exact match</option>
\t\t\t\t\t\t\t\t<option value="title">title match</option>
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t<label for="searchCase">Search case:</label>
\t\t\t\t\t\t\t\t<select name="searchCase" id="searchCase">
\t\t\t\t\t\t\t\t<option value="sensitive" selected="selected">Case sensitive</option>
\t\t\t\t\t\t\t\t<option value="insensitive">Case insensitive</option>
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t<br><label for="justplay">Timer type:</label>
\t\t\t\t\t\t\t\t<select name="justplay" id="justplay">
\t\t\t\t\t\t\t\t<option value="0" selected="selected">Record</option>
\t\t\t\t\t\t\t\t<option value="1">Zap</option>
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t<label for="overrideAlternatives">Override alternatives:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="overrideAlternatives" id="overrideAlternatives" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t<br><label for="timeSpan">TimeSpan:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="timeSpan" id="timeSpan" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="timeSpanE">
\t\t\t\t\t\t\t\t\t<label for="from">Begin:</label>
\t\t\t\t\t\t\t\t\t<input type="text" name="from" id="from" value="" class="text ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<label for="to">End:</label>
\t\t\t\t\t\t\t\t\t<input type="text" name="to" id="to" value="" class="text ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t<br><label for="timeFrame">TimeFrame:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="timeFrame" id="timeFrame" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="timeFrameE">
\t\t\t\t\t\t\t\t\t<label for="after">After:</label>
\t\t\t\t\t\t\t\t\t<input type="text" name="after" id="after" value="" class="text date ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<label for="before">Before:</label>
\t\t\t\t\t\t\t\t\t<input type="text" name="before" id="before" value="" class="text date ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t<br><label for="timerOffset">Timer offset:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="timerOffset" id="timerOffset" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="timerOffsetE">
\t\t\t\t\t\t\t\t\t<label for="obefore">Before:</label>
\t\t\t\t\t\t\t\t\t<select name="obefore" id="obefore">
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t<label for="oafter">After:</label>
\t\t\t\t\t\t\t\t\t<select name="oafter" id="oafter">
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t
\t\t\t\t\t\t\t\t<br><label for="maxDuration">Max duration:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="maxDuration" id="maxDuration" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="maxDurationE">
\t\t\t\t\t\t\t\t\t<label for="maxduration"></label>
\t\t\t\t\t\t\t\t\t<select name="maxduration" id="maxduration">
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t
\t\t\t\t\t\t\t\t<br><label for="afterevent">After event:</label>
\t\t\t\t\t\t\t\t<select name="afterevent" id="afterevent">
\t\t\t\t\t\t\t\t<option value="" selected="selected">Default</option>
\t\t\t\t\t\t\t\t<option value="none">Nothing</option>
\t\t\t\t\t\t\t\t<option value="standby">Standby</option>
\t\t\t\t\t\t\t\t<option value="shutdown">Deep Standby</option>
\t\t\t\t\t\t\t\t<option value="auto">Auto</option>
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t<span id="AftereventE">
\t\t\t\t\t\t\t\t<label for="timeSpanAE">TimeSpan:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="timeSpanAE" id="timeSpanAE" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="timeSpanAEE">
\t\t\t\t\t\t\t\t\t<label for="from">Begin:</label>
\t\t\t\t\t\t\t\t\t<input type="text" name="aefrom" id="aefrom" value="" class="text ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<label for="to">End:</label>
\t\t\t\t\t\t\t\t\t<input type="text" name="aeto" id="aeto" value="" class="text ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t
\t\t\t\t\t\t\t\t<br><label for="counter">Max Counter:</label>
\t\t\t\t\t\t\t\t<select name="counter" id="counter">
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t<span id="CounterE">
\t\t\t\t\t\t\t\t<label for="left">Left:</label>
\t\t\t\t\t\t\t\t<select name="left" id="left">
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t<select id="counterFormat" name="counterFormat" size="1">
\t\t\t\t\t\t\t\t<option value="" selected>Never</option>
\t\t\t\t\t\t\t\t<option value="%m">Monthly</option>
\t\t\t\t\t\t\t\t<option value="%U">Weekly (Sunday)</option>
\t\t\t\t\t\t\t\t<option value="%W">Weekly (Monday)</option>
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t
\t\t\t\t\t\t\t\t<br><label for="avoidDuplicateDescription">Avoid duplicate description:</label>
\t\t\t\t\t\t\t\t<select name="avoidDuplicateDescription" id="avoidDuplicateDescription">
\t\t\t\t\t\t\t\t<option value="0" selected="selected">No</option>
\t\t\t\t\t\t\t\t<option value="1">On same service</option>
\t\t\t\t\t\t\t\t<option value="2">On any service</option>
\t\t\t\t\t\t\t\t<option value="3">any service/recording</option>
\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t<br><label for="Location">Location:</label>
\t\t\t\t\t\t\t\t
\t\t\t\t\t\t\t\t<input type="checkbox" name="Location" id="Location" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="LocationE">
\t\t\t\t\t\t\t\t\t<label for="location"></label>
\t\t\t\t\t\t\t\t\t<select name="location" id="location">
''')
        for location in VFFSL(SL,"locations",True): # generated from line 147, col 11
            write(u'''\t\t\t\t\t\t\t\t\t\t\t<option value="''')
            _v = VFFSL(SL,"location",True) # u'$location' on line 148, col 27
            if _v is not None: write(_filter(_v, rawExpr=u'$location')) # from line 148, col 27.
            write(u'''">''')
            _v = VFFSL(SL,"location",True) # u'$location' on line 148, col 38
            if _v is not None: write(_filter(_v, rawExpr=u'$location')) # from line 148, col 38.
            write(u'''</option>
''')
        write(u'''\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t\t
\t\t\t\t\t\t\t\t<br><label for="Tags">Tags:</label>
\t\t\t\t\t\t\t\t\t<span id="TagsE">
\t\t\t\t\t\t\t\t\t<select data-placeholder="select tags" name="tags" id="tags" class="tags_select_box" multiple tabindex="16">
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t<br><label for="Bouquets">Bouquets:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="Bouquets" id="Bouquets" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="BouquetsE">
\t\t\t\t\t\t\t\t\t<select data-placeholder="select bouquet" name="bouquets" id="bouquets" class="bq_select_box" multiple tabindex="16">
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t<br><label for="Channels">Channels:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="Channels" id="Channels" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="ChannelsE">
\t\t\t\t\t\t\t\t\t<select data-placeholder="select channels" name="channels" id="channels" class="ch_select_box" multiple tabindex="16">
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t<br>
\t\t\t\t\t\t\t\t<br>
\t\t\t\t\t\t\t\t<div>
\t\t\t\t\t\t\t\t<label for="Filter">Filter:</label>
\t\t\t\t\t\t\t\t<input type="checkbox" name="Filter" id="Filter" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="FilterE" style="display:inline-table">
\t\t\t\t\t\t\t\t\t<input type="button" id="AddFilter" value="add"/>
\t\t\t\t\t\t\t\t\t<table id="filterlist">
\t\t\t\t\t\t\t\t\t<tr id="dummyfilter" style="display:none">
\t\t\t\t\t\t\t\t\t<td class="nopadding">
\t\t\t\t\t\t\t\t\t<select size="1" class="FT">
\t\t\t\t\t\t\t\t\t<option value="include" selected="">Include</option>
\t\t\t\t\t\t\t\t\t<option value="exclude">Exclude</option>
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</td>
\t\t\t\t\t\t\t\t\t<td class="nopadding">
\t\t\t\t\t\t\t\t\t<select size="1" class="FM">
\t\t\t\t\t\t\t\t\t<option value="title" selected="">Title</option>
\t\t\t\t\t\t\t\t\t<option value="shortdescription">Short description</option>
\t\t\t\t\t\t\t\t\t<option value="description">Description</option>
\t\t\t\t\t\t\t\t\t<option value="dayofweek">Day of week</option>
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</td>
\t\t\t\t\t\t\t\t\t<td class="nopadding">
\t\t\t\t\t\t\t\t\t<input type="text" class="FI" size="20" value="" style="display: block;">
\t\t\t\t\t\t\t\t\t<select size="1" class="FS" style="display: none;">
\t\t\t\t\t\t\t\t\t<option value="0" selected="">Monday</option>
\t\t\t\t\t\t\t\t\t<option value="1">Tuesday</option>
\t\t\t\t\t\t\t\t\t<option value="2">Wednesday</option>
\t\t\t\t\t\t\t\t\t<option value="3">Thursday</option>
\t\t\t\t\t\t\t\t\t<option value="4">Friday</option>
\t\t\t\t\t\t\t\t\t<option value="5">Saturday</option>
\t\t\t\t\t\t\t\t\t<option value="6">Sunday</option>
\t\t\t\t\t\t\t\t\t<option value="weekend">Weekend</option>
\t\t\t\t\t\t\t\t\t<option value="weekday">Weekday</option>
\t\t\t\t\t\t\t\t\t</select>
\t\t\t\t\t\t\t\t\t</td>
\t\t\t\t\t\t\t\t\t</tr>
\t\t\t\t\t\t\t\t\t</table>
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t</div>
\t\t\t\t\t\t\t\t<br><label for="vps">VPS:</label>
\t\t\t\t\t\t\t\t
\t\t\t\t\t\t\t\t<input type="checkbox" name="vps" id="vps" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t<span id="vpsE">
\t\t\t\t\t\t\t\t\t<label for="vpso">VPS Overwrite:</label>
\t\t\t\t\t\t\t\t\t\t<input type="checkbox" name="vpso" id="vpso" value="" class="checkbox ui-widget-content ui-corner-all">
\t\t\t\t\t\t\t\t\t</span>
\t\t\t\t\t\t\t\t\t
\t\t\t\t\t\t\t</fieldset>
\t\t\t\t\t\t</form>
\t\t\t\t\t\t
\t\t\t\t\t\t<div class="ui-dialog-buttonpane ui-widget-content ui-helper-clearfix">
\t\t\t\t\t\t<div id="actions">
\t\t\t\t\t\t<button id="atbutton0">ADD</button>
\t\t\t\t\t\t<button id="atbutton1">DEL</button>
\t\t\t\t\t\t<button id="atbutton2">Reload</button>
\t\t\t\t\t\t<button id="atbutton3">Save</button>
\t\t\t\t\t\t<button id="atbutton4">Parse</button>
\t\t\t\t\t\t<button id="atbutton5">Simulate</button>
\t\t\t\t\t\t<button id="atbutton6">Timers</button>
\t\t\t\t\t\t</div></div>
\t\t\t\t\t\t\t<div id="errorbox" class="timerlist_row" style="color: red;">
\t\t<div class="ui-state-error ui-corner-all" style="padding: 0 .7em;"> 
\t\t\t<p><span class="ui-icon ui-icon-alert" style="float: left; margin-right: .3em;"></span> 
\t\t\t<span id="error"></span>
\t\t\t<span id="success" style="color: green;"></span>
\t\t</div>
\t</div>
\t\t<span style="display: block;clear: both;"/>
\t\t</div>
\t\t</div>
\t</div>
\t</div>
\t</div>
</div>
<div id="simdlg" style="display:none;">
<div>
<table id="simt" border="0" class="ui-widget" style="width:99%;">
<thead class="ui-widget-header">
<tr><th>AT Name</th><th>Title</th><th>Channel</th><th>Start</th><th>End</th></tr>
</thead>
<tbody id=\'simtb\' class="ui-widget-content">
</tbody>
</table>
</div>
</div>

<div id="timerdlg" style="display:none;">
<div id="timerdlgcont">
</div>
<div>

<script type="text/javascript" src="/js/jquery-ui-timepicker-addon.min.js"></script>
<script type="text/javascript" src="/js/chosen.jquery.min.js"></script>
<script type="text/javascript" src="/js/at.js"></script>
<script type="text/javascript">
$(function() { InitPage();});
</script>
<link rel="stylesheet" type="text/css" href="/css/chosen.min.css" />
''')
        _filter = self._CHEETAH__currentFilter = _orig_filter_29289843
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_at= 'respond'

## END CLASS DEFINITION

if not hasattr(at, '_initCheetahAttributes'):
    templateAPIClass = getattr(at, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(at)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=at()).run()


